### PR TITLE
changes for finding ip address inside properties file

### PR DESCRIPTION
**Pull request by shivaharikumar**
I wanted to use the your project to fish out .properties file that has IP address hard-coded in it. Version 1.6 didn't have it and the version I forked had new rule template that can be customized with regex, tried it didn't work for me. Probably the regex I gave was too long, and so I took the privilege of adding a rule to your project and it works fine as I wanted, thought you might be interested in it.

**Rule : IP address hardcoded in properties . MAJOR . 5 mins debt**
Class : IPAddressCheck.java
Description : ip-address.html

Unintentionally I indented your CheckList class, hope that is not a big mess up.

Cheers,
Shiva

### CODE REVIEW

**Comment by racodond** [comment]
Hi @pbshiva,

First, thanks for your interest in the plugin and for your PR.

The plugin only provides rules to define regular expressions on keys or comments. What you need is a rule to define regular expressions on values. I'll implement this rule in the upcoming version so that you'll be able to detect hard-coded IP addresses. See https://github.com/racodond/sonar-jproperties-plugin/issues/33

Thus I'm closing the PR.

Have a good day!

David

**Comment by shivaharikumar** [comment]
Ciao David
Cool then :+1:

**Comment by racodond** [comment]
Hi @pbshiva,

A release candidate that fixes your issue is available: https://groups.google.com/d/msg/sonarqube/HIaI_obeWOY/YdZ-gwn1BQAJ

Your feedback is more than welcome!

Thank you

David

**Comment by shivaharikumar** [comment]
Works like charm :+1: 

I experimented with couple of regex and finally this one worked for me. (Just in case any one is looking for regex that will work with this plugin for ip address)
`^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$`

**Comment by shivaharikumar** [comment]
Note: The new version that I tried (2.0 - SNAPSHOT) support latest LTS - SQ 5.6. So if a person like me who is in an large enterprise setup who can not upgrade SQ at their own wish can't use this new feature.

In such case, release version like `1.6 - 1.7` and adding this pull request will work fine. Or can get the same directly from my repo https://github.com/pbshiva/sonar-jproperties-plugin

**Pull request closed without merging**
