### PR TITLE
Set encoding specified by the user instead of the hardcoded value (always ISO-8859-1)

### PR DESCRIPTION
**Pull request by agabrys**
Hi,
We hit an error during analysis:

```
10:56:34 [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar (default-cli) on project sonarqube-falsepositives: Unable to analyse file: /var/lib/jenkins/jobs/sonarqube-falsepositives/workspace/src/main/resources/messages_zh.properties: Unable to highlight file src/main/resources/messages_zh.properties: 12 is not a valid line offset for pointer. File src/main/resources/messages_zh.properties has 8 character(s) at line 3 -> [Help 1]
10:56:34 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar (default-cli) on project sonarqube-falsepositives: Unable to analyse file: /var/lib/jenkins/jobs/sonarqube-falsepositives/workspace/src/main/resources/messages_zh.properties
...
10:56:34 Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to analyse file: /var/lib/jenkins/jobs/sonarqube-falsepositives/workspace/src/main/resources/messages_zh.properties
...
10:56:34 Caused by: org.sonar.squidbridge.api.AnalysisException: Unable to analyse file: /var/lib/jenkins/jobs/sonarqube-falsepositives/workspace/src/main/resources/messages_zh.properties
...
10:56:34 Caused by: java.lang.IllegalArgumentException: Unable to highlight file src/main/resources/messages_zh.properties
...
10:56:34 Caused by: java.lang.IllegalArgumentException: 12 is not a valid line offset for pointer. File src/main/resources/messages_zh.properties has 8 character(s) at line 3
```

I analyzed the problem and found a reason why it has occurred. It is caused by an incorrect encoding. The plugin always parses files by using `ISO-8859-1`, but my sources are encoded in `UTF-8` (I set it by `<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>`).

After this small change files have been analyzed successfully.

You can test it by using the following file ([download zip](https://github.com/racodond/sonar-jproperties-plugin/files/1815260/messages_zh.zip)):
```


dummy=虚拟
```

Regards

### CODE REVIEW

**Comment by agabrys** [comment]
Builds for LTS environment have failed, but I don't think that my change is the cause.

**Comment by racodond** [comment]
Hi @agabrys,

`Filesystem.encondig()` returns the encoding of the files of the project, not the encoding of a specific file. See https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/batch/fs/FileSystem.java#L63.

For a long time (but it's been changing), Java code was encoded in UTF-8 and Java properties in ISO-8859-1 (as it was mandatory). Unfortunately, there's no way in SonarQube to define different encodings for different files... See https://jira.sonarsource.com/browse/SONAR-8688.

So, it won't work...

Regards,

**Comment by agabrys** [comment]
> Filesystem.encondig() returns the encoding of the files of the project, not the encoding of a specific file. See https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/batch/fs/FileSystem.java#L63.

I know that 😄 That is exactly what I want (we have all files encoded in `UTF-8`). I understand that you don't want to change the default behavior, but can we parameterize it somehow?

```
private static final String DEFAULT_CHARSET = "ISO-8859-1";

public JavaPropertiesSquidSensor(...) {
    ...
    this.charset = resolveCharset(fileSystem);
    ...
}

protected Charset resolveCharset(final FileSystem fileSystem) {
    final String encoding = System.getProperty("sonar.jproperties.encoding", DEFAULT_CHARSET);
    if ("project".equalsIgnoreCase(encoding)) {
        return fileSystem.encoding();
    }
    if (encoding.trim().isEmpty()) {
         // maybe somebody initialized the property with a blank value
        return Charset.forName(DEFAULT_CHARSET);
    }
    return Charset.forName(encoding);
}
```

`sonar.jproperties.encoding` stores charset code or `project` which means the same as `sonar.encoding`

btw. Luckily JDK9 uses `UTF-8` by default to parse localization bundles: https://docs.oracle.com/javase/9/intl/internationalization-enhancements-jdk-9.htm#JSINT-GUID-974CF488-23E8-4963-A322-82006A7A14C7

**Comment by racodond** [comment]
Sure!

I tried something about a year ago. See commits from February 28, 2017 and February 27, 2017. But I don't really remember if it worked and what happened... If you want to have a look, feel free to have a look!

**Comment by agabrys** [comment]
Ok, I'll try do it this month.
I'm closing this PR.

Regards

**Comment by racodond** [comment]
It would be great!

**Pull request closed without merging**
